// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Sample
{
	public partial class MyTableViewController : UITableViewController
	{
		public MyTableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
